version: "3"
services:
  golang:
    build:
      context: ./services/golang
    container_name: go
    networks:
      - default

  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    container_name: nginx
    networks:
      - default

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    networks:
      - default

  elasticsearch:
    build:
      context: ./services/elasticsearch
    container_name: elasticsearch
    networks:
      - default


networks:
  default: